### PR TITLE
allow using Trans with embedded_schema

### PR DESCRIPTION
**Pull request by sfusato**
I'm using Trans and I love it :heart: . Recently, I've added a new model to one of my projects and this time I've wanted to approach differently the translation part. I've investigated what it would take to allow Trans to make use of `embedded_schema`. It seems not much. The only change was regarding how to fetch the translations, since all the keys would be atoms now instead of strings in the Ecto loaded struct.

### Why `embedded_schema` ?
* higher flexibility being able to make validations, transformations using the embedded_schema's own changeset
* far easier to work with forms: use `inputs_for` and display by default any changeset errors
* more explicit in how everything works under the hood

All of the above was still possible before, but required some hacking working with nested maps: `model > translations > locale > field`.

### Example

```diff
defmodule Model do
  use Trans, translates: [:name, :slug, :description, :overview]

  schema "models" do
-    field :translations, :map
+    embeds_one :translations, Translations, on_replace: :update
  end

  def changeset(model, attrs) do
    model
-    |> cast(attrs, [:translations])
+    |> cast_embed(:translations)
  end
end
```

```elixir
defmodule Model.Translations do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key false
  embedded_schema do
    embeds_one :it, Fields, on_replace: :update
    embeds_one :fr, Fields, on_replace: :update
  end

  def changeset(translations, attrs) do
    translations
    |> cast(attrs, [])
    |> cast_embed(:it)
    |> cast_embed(:fr)
  end
end
```
The `embedded_schema` in `Fields` would declare the same fields as in in the `Model` module: `use Trans, translates: [:name, :slug, :description, :overview]`

```elixir
defmodule Model.Translations.Fields do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key false
  embedded_schema do
    field :name, :string
    field :slug, :string
    field :description, :string
    field :overview, :string
  end

  def changeset(translation_fields, attrs) do
    translation_fields
    |> cast(attrs, [:name, :slug, :description, :overview])
    |> validate_length(:name, min: 10, max: 256)
  end
end
```

```elixir
  # somewhere in the template
  <%= translated_text_field(:it, f, :name) %>

  # some helper
  defp translated_text_field(locale, form, field) when is_atom(locale) do
    inputs_for(form, :translations, fn translations ->
      inputs_for(translations, locale, fn locale ->
        ~E"""
        <%= text_input(locale, field, class: "form-control form-control-lg") %>
        <%= AppWeb.ErrorHelpers.error_tag locale, field %>
        """
      end)
    end)
  end
```

This doesn't bring any breaking changes, but just extends the usage from `:map` to also `embedded_schema`

### CODE REVIEW

**Comment by crbelaus** [comment]
Looks great!
I am a bit short of time this month, but I will come back to this PR as soon as possible.

Thank you very much @sfusato 🙌

**Comment by RxAssim** [comment]
This is brilliant @sfusato. It will help a lot with validating inputs.

**Comment by adrianplavka** [comment]
I'm also interested in having this upstream.

Any updates on this PR @crbelaus ?

**Review by crbelaus — CHANGES_REQUESTED** [review]
Sorry for the super-late review. Life got in the way and I didn't have any time to spare after work.

The implementation looks superb 🙇 I am eager to merge this pull request and release a new Trans version. The only missing piece would be to add a test that uses the embedded schema approach for translations.
Also, the documentation should be improved to explain this use-case. The example of the pull request serves perfectly.

**Review by crbelaus — APPROVED** [review]
As I've commented on the other open PRs, I've changed my mind.

Instead of having this perfectly working code waiting in the limbo. I think that it is a better idea to merge it now. I an add the documentation later before releasing a new version of the library.

Thank you very much for your work @sfusato 🙇

**Comment by crbelaus** [comment]
I've merge this PR using the command line so I could fix the merge conflicts at the moment.

Thanks again @sfusato !! 🙌

**Comment by krns** [comment]
Thanks for merging this! @crbelaus, do you know when this will be released?

**Comment by crbelaus** [comment]
Thanks @krns!

I am adding tests to this functionality to ensure that it works properly alongside the new `translate/2` function added in #67. Using plain maps for translations is still supported, but I will also update the documentation to indicate that using embedded schemas is the preferred way for the reasons explained by @sfusato in this PR.

Since I am working on this in my free time (of which I don't have much at the time) releasing a new version may take a while. In the meantime [you can use the `master` branch directly in your project.](https://hexdocs.pm/mix/Mix.Tasks.Deps.html)

**Pull request closed without merging**
